### ISSUE TITLE
stuff not working how to fix

### ISSUE THREAD

**Issue by mypugisold91** [JarikDem-Bot/ai-waifu#10]
Open error: is JACK server running?
Traceback (most recent call last):
  File "c:\Users\pugja\OneDrive\Desktop\ai-waifu\main.py", line 25, in <module>
    main()
  File "c:\Users\pugja\OneDrive\Desktop\ai-waifu\main.py", line 13, in main
    personality_file = personality.txt,
NameError: name 'personality' is not defined

**Comment by mypugisold91** [comment]
thanks
